# NOTE: open-pull-requests-limit: 0 is used until
# https://github.com/dependabot/dependabot-core/issues/1828 is fixed

version: 2
updates:
  - package-ecosystem: "devcontainers"
    open-pull-requests-limit: 0
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    open-pull-requests-limit: 0
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "uv"
    open-pull-requests-limit: 0
    directory: "/"
    schedule:
      interval: "weekly"
